name = "signup-worker"
type = "webpack"
account_id = "394d48aba686b2466fe12e540c5d9466"
workers_dev = true
route = ""
zone_id = "ebdbcc9f178b7b36f9768e6ec55972d6"
webpack_config = "webpack.config.js"
vars = { PLAID_ORIGIN = "https://production.plaid.com", DUES_PRODUCT_ID = "prod_LKLGmaCbfcvwHk", DUES_SIGNUP_PRICE_ID = "price_1Kdgj3JGGmDnSmnt40qesLxB", CARD_FEE_PRODUCT_ID = "prod_M2BZrfLu49i6Yi", SENDGRID_DYNAMIC_TEMPLATE = "d-13f0fbb904dd4dfc991d15a05365943b" }

[dev]
port = 8787