[package]
name = "signup_service"
version = "0.1.0"
authors = ["Jonah Dahlquist <hi@jonah.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
