baseURL = "/"
languageCode = "en-us"
title = "Alphabet Workers Union"
assetDir = ".assets"
staticDir = ".static"
resourceDir = ".resources"
publishDir = ".public"
disableKinds = ["taxonomy", "term"]
[params]
  twitter = "alphabetworkers"
  instagram = "alphabetworkers"
  facebook = "alphabetworkers"
  contact_url = "mailto:contact@alphabetworkersunion.org"
  images = ["img/static/og-banner.png"]
  title = "Alphabet Workers Union"
  member_count = 1400
languageCode = "en-us"
[author]
  name = "Alphabet Workers Union"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
defaultLanguageContent = "en"
[languages]
  [languages.en]
  [languages.es]
[markup.goldmark.renderer]
 unsafe = true